import Account from './Account/Account'
import Button from './Button/Button'
import Category from './Category/Category'
import Fav from './Fav/Fav'
import Feedback from './Feedback/Feedback'
import Form from './Form/Form'
import Gif from './Gif/Gif'
import Header from './Header/Header'
import ListOfGifs from './ListOfGifs/ListOfGifs'
import Modal from './Modal/Modal'
import Ratings from './Ratings/Ratings'
import Searcher from './Searcher/Searcher'
import Spinner from './Spinner/Spinner'
import TrendingSearches from './TrendingSearches/TrendingSearches'

export { Gif, ListOfGifs, Searcher, TrendingSearches, Category, Spinner, Header, Account, Form, Feedback, Ratings, Fav, Modal, Button }
